version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: article-sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    restart: always

  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./init.sql:/init.sql
    entrypoint: >
      /bin/bash -c "
      sleep 25 &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P YourStrong!Passw0rd -i /init.sql
      "

  api-1:
    build: .
    image: happyheaders-api:latest
    ports:
      - "5199:5199"
    environment:                    
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:                     
      - sqlserver
  
  api-2:
    image: happyheaders-api:latest
    ports:
      - "5200:5199"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:                     
      - sqlserver

volumes:
  sqlvolume: